import { StyleSheet } from "react-native";

export const avatarStudioStyles = StyleSheet.create({
  studio: {
    width: "100%",
    gap: 26,
    padding: 22,
    borderRadius: 26,
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "#EEEEF0",
  },
  introduction: { gap: 7 },
  title: { color: "#172126", fontSize: 24, fontWeight: "600", letterSpacing: -0.6 },
  description: { color: "#697176", fontSize: 13, lineHeight: 20 },
  hint: { color: "#7C8387", fontSize: 11, lineHeight: 17 },
  layout: { gap: 30, alignItems: "flex-start" },
  portraitColumn: { width: "100%", gap: 13 },
  preview: {
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 18,
    gap: 6,
    borderRadius: 24,
    backgroundColor: "#FAFAF9",
    overflow: "hidden",
  },
  characterName: {
    color: "#172126",
    fontSize: 19,
    fontWeight: "600",
    letterSpacing: -0.4,
    paddingHorizontal: 10,
    textAlign: "center",
  },
  creationColumn: { flex: 1, width: "100%", minWidth: 0, gap: 14 },
  motionRow: {
    flexDirection: "row",
    padding: 4,
    gap: 3,
    borderRadius: 22,
    backgroundColor: "#F5F5F4",
  },
  motionButton: {
    flex: 1,
    minHeight: 36,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 18,
  },
  motionSelected: { backgroundColor: "#FFFFFF" },
  motionText: { color: "#586368", fontSize: 11, fontWeight: "500" },
  notice: { gap: 10, padding: 13, backgroundColor: "#F7F8F8", borderRadius: 16 },
  generation: { gap: 14, paddingTop: 4 },
  progress: { flexDirection: "row", alignItems: "center", gap: 10, minHeight: 32 },
  sectionTitle: { color: "#263137", fontSize: 15, fontWeight: "600", letterSpacing: -0.2 },
  candidates: { gap: 12, width: "100%", maxWidth: 430, alignSelf: "center" },
  candidateRow: { flexDirection: "row", gap: 12 },
  candidate: {
    flex: 1,
    minWidth: 0,
    backgroundColor: "#F8F9F9",
    borderRadius: 20,
    padding: 8,
    gap: 4,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 2,
    borderColor: "transparent",
    overflow: "hidden",
  },
  candidateSelected: { borderColor: "#4398DE", backgroundColor: "#F1F8FE" },
  candidateDimmed: { opacity: 0.48 },
  optionText: { color: "#67747C", fontSize: 11, paddingBottom: 5 },
  check: {
    position: "absolute",
    right: 9,
    top: 9,
    width: 21,
    height: 21,
    borderRadius: 12,
    backgroundColor: "#4398DE",
    alignItems: "center",
    justifyContent: "center",
  },
  checkText: { color: "#FFFFFF", fontSize: 13, fontWeight: "700" },
  actions: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
  gallerySection: { borderTopWidth: 1, borderTopColor: "#ECEFF0", paddingTop: 22, gap: 16 },
  galleryHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  gallery: { flexDirection: "row", flexWrap: "wrap", gap: 12 },
  savedCard: {
    width: 122,
    minHeight: 152,
    alignItems: "center",
    padding: 10,
    gap: 5,
    backgroundColor: "#FAFAF9",
    borderRadius: 20,
    borderWidth: 2,
    borderColor: "transparent",
    overflow: "hidden",
  },
  savedName: { color: "#425059", fontSize: 11, lineHeight: 15, textAlign: "center" },
  activeLabel: { color: "#2E85C5", fontSize: 10, fontWeight: "600" },
});
