import { StyleSheet } from "react-native";
import type { ThemeColors } from "./theme-palette";

export const avatarStudioStyles = (colors: ThemeColors) =>
  StyleSheet.create({
    studio: {
      width: "100%",
      gap: 26,
      padding: 22,
      borderRadius: 26,
      backgroundColor: colors.card,
      borderWidth: 1,
      borderColor: colors.line,
    },
    introduction: { gap: 7 },
    title: { color: colors.text, fontSize: 24, fontWeight: "600", letterSpacing: -0.6 },
    description: { color: colors.muted, fontSize: 13, lineHeight: 20 },
    hint: { color: colors.muted, fontSize: 11, lineHeight: 17 },
    layout: { gap: 30, alignItems: "flex-start" },
    portraitColumn: { width: "100%", gap: 13 },
    preview: {
      alignItems: "center",
      justifyContent: "center",
      paddingVertical: 18,
      gap: 6,
      borderRadius: 24,
      backgroundColor: colors.raised,
      overflow: "hidden",
    },
    characterName: {
      color: colors.text,
      fontSize: 19,
      fontWeight: "600",
      letterSpacing: -0.4,
      paddingHorizontal: 10,
      textAlign: "center",
    },
    creationColumn: { flex: 1, width: "100%", minWidth: 0, gap: 14 },
    motionRow: {
      flexDirection: "row",
      padding: 4,
      gap: 3,
      borderRadius: 22,
      backgroundColor: colors.subtle,
    },
    motionButton: {
      flex: 1,
      minHeight: 36,
      alignItems: "center",
      justifyContent: "center",
      borderRadius: 18,
    },
    motionSelected: { backgroundColor: colors.card },
    motionText: { color: colors.muted, fontSize: 11, fontWeight: "500" },
    notice: { gap: 10, padding: 13, backgroundColor: colors.raised, borderRadius: 16 },
    generation: { gap: 14, paddingTop: 4 },
    progress: { flexDirection: "row", alignItems: "center", gap: 10, minHeight: 32 },
    sectionTitle: { color: colors.text, fontSize: 15, fontWeight: "600", letterSpacing: -0.2 },
    candidates: { gap: 12, width: "100%", maxWidth: 430, alignSelf: "center" },
    candidateRow: { flexDirection: "row", gap: 12 },
    candidate: {
      flex: 1,
      minWidth: 0,
      backgroundColor: colors.raised,
      borderRadius: 20,
      padding: 8,
      gap: 4,
      alignItems: "center",
      justifyContent: "center",
      borderWidth: 2,
      borderColor: "transparent",
      overflow: "hidden",
    },
    candidateSelected: { borderColor: colors.selectedBorder, backgroundColor: colors.raised },
    candidateDimmed: { opacity: 0.48 },
    optionText: { color: colors.muted, fontSize: 11, paddingBottom: 5 },
    check: {
      position: "absolute",
      right: 9,
      top: 9,
      width: 21,
      height: 21,
      borderRadius: 12,
      backgroundColor: "#4398DE",
      alignItems: "center",
      justifyContent: "center",
    },
    checkText: { color: colors.onFeature, fontSize: 13, fontWeight: "700" },
    actions: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
    gallerySection: { borderTopWidth: 1, borderTopColor: colors.line, paddingTop: 22, gap: 16 },
    galleryHeader: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      gap: 12,
    },
    gallery: { flexDirection: "row", flexWrap: "wrap", gap: 12 },
    savedItem: { width: 122, alignItems: "stretch" },
    renameButton: { minHeight: 44, alignItems: "center", justifyContent: "center" },
    renameText: { color: colors.blueDark, fontSize: 12, fontWeight: "600" },
    savedCard: {
      width: 122,
      minHeight: 152,
      alignItems: "center",
      padding: 10,
      gap: 5,
      backgroundColor: colors.raised,
      borderRadius: 20,
      borderWidth: 2,
      borderColor: "transparent",
      overflow: "hidden",
    },
    savedName: { color: colors.muted, fontSize: 11, lineHeight: 15, textAlign: "center" },
    activeLabel: { color: colors.blueDark, fontSize: 10, fontWeight: "600" },
  });
