/** English keys feed the app-wide locale catalog; user-created names are never translated. */
export const avatarPTBR: Record<string, string> = {
  "Your companion": "Seu companheiro",
  "Choose a 3D companion or create your own. The live preview reacts as you edit.":
    "Escolha um companheiro 3D ou crie o seu. A prévia ao vivo reage às suas mudanças.",
  "3D companion preview": "Prévia do companheiro 3D",
  "Animated 3D companion": "Companheiro 3D animado",
  "Static preview · 3D unavailable on this device":
    "Prévia estática · 3D indisponível neste dispositivo",
  "Loading your companion…": "Carregando seu companheiro…",
  "Live 3D preview": "Prévia 3D ao vivo",
  "Motion follows your device’s accessibility settings.":
    "O movimento segue as configurações de acessibilidade do dispositivo.",
  "Ready-made companions": "Companheiros prontos",
  Capybara: "Capivara",
  Wolf: "Lobo",
  Fox: "Raposa",
  Cat: "Gato",
  Robot: "Robô",
  "Create your own": "Crie o seu",
  "Custom companion": "Companheiro personalizado",
  "Start from the current companion and make it yours.":
    "Comece com o companheiro atual e deixe-o do seu jeito.",
  Species: "Espécie",
  "Body shape": "Formato do corpo",
  Round: "Arredondado",
  Balanced: "Equilibrado",
  Slender: "Esbelto",
  "Body color": "Cor do corpo",
  "Accent color": "Cor dos detalhes",
  "Eye color": "Cor dos olhos",
  "Custom body color": "Cor personalizada do corpo",
  "Custom accent color": "Cor personalizada dos detalhes",
  "Custom eye color": "Cor personalizada dos olhos",
  "Use a six-digit hex color, such as #8299AC.":
    "Use uma cor hexadecimal de seis dígitos, como #8299AC.",
  Accessory: "Acessório",
  None: "Nenhum",
  Scarf: "Cachecol",
  Glasses: "Óculos",
  Leaf: "Folha",
  Headphones: "Fones de ouvido",
  "Preview animation": "Animação da prévia",
  Idle: "Em repouso",
  Thinking: "Pensando",
  Talking: "Falando",
  "Save companion": "Salvar companheiro",
  "Companion saved": "Companheiro salvo",
  "Changes are not saved yet": "As mudanças ainda não foram salvas",
  "Your saved companion": "Seu companheiro salvo",
  "Restore saved design": "Restaurar aparência salva",
  "Could not load your companion. Try again.":
    "Não foi possível carregar seu companheiro. Tente novamente.",
  "Could not save your companion. Your changes are still here.":
    "Não foi possível salvar seu companheiro. Suas mudanças continuam aqui.",
  "Try again": "Tentar novamente",
  "Choose {name}": "Escolher {name}",
  "Choose {name} color": "Escolher a cor {name}",
  "Warm sand": "Areia quente",
  "Cloud blue": "Azul nuvem",
  "Soft lilac": "Lilás suave",
  "Fox orange": "Laranja raposa",
  "Sage green": "Verde sálvia",
  Cream: "Creme",
  "Rose pink": "Rosa claro",
  Charcoal: "Carvão",
  Teal: "Verde azulado",
  Hazel: "Avelã",
  "The avatar changes appearance only. Edit name and personality in settings.":
    "O avatar altera apenas a aparência. Edite o nome e a personalidade nas configurações.",
};
