export const chatPresentationPtBR: Record<string, string> = {
  "Review action": "Revisar ação",
  Close: "Fechar",
  History: "Histórico",
  "Email draft": "Rascunho de e-mail",
  "Connected account": "Conta conectada",
  "Account not specified": "Conta não informada",
  "View action details": "Ver detalhes da ação",
  "What you asked": "O que você pediu",
  "What was delivered": "O que foi entregue",
  "What happened": "O que aconteceu",
  "Progress so far": "Andamento",
  "Task cancelled": "Tarefa cancelada",
  "Action declined": "Ação recusada",
  "Your approval is needed": "Aguardando sua aprovação",
  "Your answer is needed": "O que preciso saber de você",
  "{count} steps": "{count} etapas",
  "Step {number}": "Etapa {number}",
  "Choose Workspace tools": "Selecionando ferramentas do Google",
  "Check tool requirements": "Conferindo os dados necessários",
  "Check connected accounts": "Conferindo as contas conectadas",
  "Prepare event removal": "Preparando a exclusão do compromisso",
  "Remove event": "Remover compromisso",
  "Create event": "Criar compromisso",
  "Edit event": "Alterar compromisso",
  "Find calendar events": "Buscar compromissos",
  "Read calendar event": "Consultar compromisso",
  "Read calendar settings": "Conferir configurações da agenda",
  "Find calendars": "Buscar agendas",
  "Edit calendar settings": "Alterar configurações da agenda",
  "Clear calendar": "Limpar agenda",
  "Check availability": "Conferir disponibilidade",
  "Primary calendar": "Agenda principal",
  "Send email": "Enviar e-mail",
  "Save email draft": "Salvar rascunho de e-mail",
  "Move email to trash": "Mover e-mail para a lixeira",
  "Delete email": "Excluir e-mail",
  "Delete email draft": "Excluir rascunho de e-mail",
  "Change email labels": "Alterar marcadores de e-mail",
  "Find emails": "Buscar e-mails",
  "Read email": "Ler e-mail",
  "Create file": "Criar arquivo",
  "Delete file": "Excluir arquivo",
  "Read file": "Ler arquivo",
  "Find file": "Buscar arquivos",
  "Copy file": "Copiar arquivo",
  "Edit file": "Alterar arquivo",
  "Create document": "Criar documento",
  "Delete document": "Excluir documento",
  "Read document": "Ler documento",
  "Find document": "Buscar documentos",
  "Copy document": "Copiar documento",
  "Edit document": "Editar documento",
  "Clear document": "Limpar documento",
  "Create spreadsheet": "Criar planilha",
  "Delete spreadsheet": "Excluir planilha",
  "Read spreadsheet": "Ler planilha",
  "Find spreadsheet": "Buscar planilhas",
  "Copy spreadsheet": "Copiar planilha",
  "Edit spreadsheet": "Editar planilha",
  "Clear spreadsheet": "Limpar planilha",
  "Add rows to spreadsheet": "Adicionar linhas à planilha",
  "Create presentation": "Criar apresentação",
  "Delete presentation": "Excluir apresentação",
  "Read presentation": "Ler apresentação",
  "Find presentation": "Buscar apresentações",
  "Copy presentation": "Copiar apresentação",
  "Edit presentation": "Editar apresentação",
  "Clear presentation": "Limpar apresentação",
  "Update connected account": "Alterar conta conectada",
  "Deletion was declined. This item was not removed.":
    "Você recusou a exclusão. Este item não foi removido.",
  "You declined this action. It was not executed.":
    "Você recusou esta ação. Ela não foi executada.",
  "This action was cancelled.": "Esta ação foi cancelada.",
  "This approval expired. A new review is required before making changes.":
    "Esta aprovação expirou. É preciso revisar uma nova ação antes de fazer alterações.",
  "Removal confirmed.": "Remoção confirmada.",
  "Change completed.": "Alteração concluída.",
  "This action could not be completed. See the error below.":
    "Não foi possível concluir esta ação. Veja o erro abaixo.",
  "The result has not been confirmed. Do not repeat this action yet.":
    "O resultado ainda não foi confirmado. Aguarde antes de repetir esta ação.",
  "The approved action is being executed.": "A ação aprovada está sendo executada.",
  "Review the item and account. Nothing is removed until you approve.":
    "Confira o item e a conta. Nada será removido até você aprovar.",
  "Review the details before approving this change.":
    "Confira os detalhes antes de aprovar esta alteração.",
};
