import { StyleSheet } from "react-native";
import { colors } from "./ui";

export const desktopStyles = StyleSheet.create({
  shell: { flex: 1, flexDirection: "row", minHeight: 0 },
  sidebar: {
    width: 240,
    backgroundColor: "#F5F7FA",
    borderRightWidth: 1,
    borderRightColor: "#E7EBF0",
    paddingHorizontal: 16,
    paddingTop: 24,
    paddingBottom: 18,
    gap: 20,
  },
  brand: { flexDirection: "row", alignItems: "center", gap: 10, paddingHorizontal: 8 },
  brandName: { fontSize: 17, fontWeight: "700", color: colors.text, letterSpacing: -0.5 },
  brandCaption: { fontSize: 11, color: colors.muted, marginTop: 3 },
  newChat: {
    minHeight: 44,
    borderRadius: 12,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    backgroundColor: "#205C91",
  },
  newChatText: { color: "#FFFFFF", fontSize: 13, fontWeight: "600" },
  navigation: { gap: 4 },
  navItem: {
    minHeight: 42,
    borderRadius: 10,
    paddingHorizontal: 12,
    flexDirection: "row",
    alignItems: "center",
    gap: 11,
  },
  navLabel: { fontSize: 13, fontWeight: "500", color: "#52606B", flexShrink: 1 },
  activeItem: { backgroundColor: "#E4EDF7" },
  activeLabel: { color: "#205C91", fontWeight: "600" },
  divider: { height: 1, backgroundColor: "#E3E8EE" },
  conversations: { flex: 1, minHeight: 0 },
  conversationHeading: {
    paddingHorizontal: 12,
    marginBottom: 8,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  sectionLabel: { color: "#87919A", fontSize: 11, fontWeight: "600" },
  menuButton: {
    width: 28,
    height: 28,
    borderRadius: 7,
    alignItems: "center",
    justifyContent: "center",
  },
  conversationItem: { minHeight: 36, paddingHorizontal: 12, gap: 9 },
  conversationLabel: { fontSize: 12, color: "#66727D", flex: 1 },
  customize: {
    borderRadius: 14,
    padding: 12,
    gap: 10,
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "#E5EAF0",
  },
  customizeCaption: { color: colors.muted, fontSize: 11, lineHeight: 17 },
  customizeAction: { flexDirection: "row", alignItems: "center", gap: 7 },
  customizeLabel: { fontSize: 12, color: "#205C91", fontWeight: "600" },
  main: { flex: 1, minWidth: 0, minHeight: 0, backgroundColor: colors.canvas },
  header: {
    minHeight: 88,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 20,
    paddingHorizontal: 32,
    paddingVertical: 18,
    borderBottomWidth: 1,
    borderBottomColor: "#EEF0F3",
    backgroundColor: "#FFFFFF",
  },
  headerTitle: { color: colors.text, fontSize: 18, fontWeight: "600", letterSpacing: -0.5 },
  headerSubtitle: { color: "#78848D", fontSize: 12, marginTop: 5 },
  headerActions: { flexDirection: "row", alignItems: "center", gap: 16 },
  notification: { position: "relative" },
  badge: {
    width: 7,
    height: 7,
    borderRadius: 4,
    position: "absolute",
    right: 10,
    top: 8,
    backgroundColor: "#205C91",
    borderColor: "#FFFFFF",
    borderWidth: 1,
  },
  content: { flex: 1, minHeight: 0 },
  chat: {
    flex: 1,
    width: "100%",
    maxWidth: 900,
    alignSelf: "center",
    minHeight: 0,
    paddingHorizontal: 26,
    paddingTop: 14,
    paddingBottom: 24,
  },
  page: { width: "100%", maxWidth: 1160, alignSelf: "center", padding: 32, paddingBottom: 44 },
  pageTitle: { color: colors.text, fontSize: 28, fontWeight: "600", letterSpacing: -0.8 },
  pageSubtitle: {
    color: colors.muted,
    fontSize: 14,
    lineHeight: 22,
    marginTop: 8,
    marginBottom: 26,
  },
  settings: { gap: 24, alignItems: "flex-start" },
  settingsProfile: { flex: 1, minWidth: 0, gap: 22 },
  settingsAside: { width: 292, gap: 22 },
  appearance: { borderWidth: 1, borderColor: "#E9EDF2", gap: 16 },
  avatarOptions: { flexDirection: "row", gap: 10, justifyContent: "center" },
  avatarOption: { padding: 6, borderWidth: 2, borderRadius: 18 },
});
