import { StyleSheet } from "react-native";
import { colors } from "./ui";

export const desktopStyles = StyleSheet.create({
  shell: { flex: 1, flexDirection: "row", minHeight: 0, backgroundColor: colors.canvas },
  rail: {
    width: 66,
    borderRightWidth: 1,
    borderRightColor: colors.line,
    paddingVertical: 18,
    alignItems: "center",
    justifyContent: "space-between",
  },
  railNavigation: { gap: 9, paddingTop: 74 },
  railUtilities: { gap: 10 },
  railItem: {
    width: 42,
    height: 42,
    borderRadius: 22,
    alignItems: "center",
    justifyContent: "center",
  },
  sidebar: {
    width: 218,
    flexShrink: 0,
    borderRightWidth: 1,
    borderRightColor: colors.line,
    paddingTop: 15,
  },
  sideChatToolbar: { flexDirection: "row", alignItems: "center", paddingHorizontal: 12, gap: 5 },
  search: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#EFEFF1",
    borderRadius: 22,
    gap: 7,
    paddingHorizontal: 11,
    height: 34,
  },
  searchInput: { flex: 1, minWidth: 0, color: colors.text, fontSize: 12, paddingVertical: 4 },
  menuButton: {
    width: 30,
    height: 30,
    borderRadius: 15,
    alignItems: "center",
    justifyContent: "center",
  },
  conversations: { flex: 1, minHeight: 0 },
  sectionLabel: { color: colors.muted, fontSize: 11, fontWeight: "500" },
  conversationItem: {
    minHeight: 54,
    borderRadius: 11,
    paddingHorizontal: 10,
    paddingVertical: 10,
    gap: 10,
    flexDirection: "row",
    alignItems: "center",
  },
  conversationLabel: { fontSize: 12, color: colors.text, lineHeight: 17 },
  conversationDate: { color: "#97979B", fontSize: 10 },
  sideChatEmpty: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 22,
    gap: 11,
    paddingBottom: 38,
  },
  sideChatEmptyTitle: { fontSize: 13, color: colors.text, fontWeight: "500", textAlign: "center" },
  sideChatEmptyCopy: {
    fontSize: 12,
    color: colors.muted,
    textAlign: "center",
    lineHeight: 18,
    marginBottom: 5,
  },
  activeItem: { backgroundColor: "#ECECEE" },
  main: { flex: 1, minWidth: 0, minHeight: 0, backgroundColor: colors.canvas },
  header: {
    minHeight: 66,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 20,
    paddingHorizontal: 28,
    paddingVertical: 14,
  },
  headerTitle: { color: colors.text, fontSize: 16, fontWeight: "500", letterSpacing: -0.3 },
  headerActions: { flexDirection: "row", alignItems: "center", gap: 12 },
  chatHeader: { minHeight: 58, height: 58, paddingHorizontal: 20, paddingVertical: 10 },
  notification: { position: "relative" },
  badge: {
    width: 6,
    height: 6,
    borderRadius: 3,
    position: "absolute",
    right: 9,
    top: 9,
    backgroundColor: colors.blueDark,
    borderColor: colors.canvas,
    borderWidth: 1,
  },
  content: { flex: 1, minHeight: 0 },
  chat: {
    flex: 1,
    width: "100%",
    maxWidth: 744,
    alignSelf: "center",
    minHeight: 0,
    paddingHorizontal: 28,
    paddingBottom: 18,
  },
  inspector: { width: 294, flexShrink: 0, borderLeftWidth: 1, borderLeftColor: colors.line },
  inspectorToolbar: {
    flexDirection: "row",
    justifyContent: "flex-end",
    alignItems: "center",
    paddingHorizontal: 14,
    paddingTop: 12,
    height: 42,
  },
  inspectorProfile: {
    alignItems: "center",
    paddingHorizontal: 24,
    paddingTop: 4,
    paddingBottom: 34,
    gap: 7,
  },
  inspectorPortrait: {
    width: 108,
    height: 108,
    borderRadius: 54,
    backgroundColor: "#F0F0F0",
    marginBottom: 3,
  },
  portraitEdit: {
    position: "absolute",
    right: -1,
    bottom: 0,
    width: 30,
    height: 30,
    borderRadius: 16,
    backgroundColor: colors.canvas,
    borderWidth: 3,
    borderColor: colors.canvas,
    justifyContent: "center",
    alignItems: "center",
  },
  inspectorName: { color: colors.text, fontSize: 21, fontWeight: "500", letterSpacing: -0.6 },
  inspectorStatus: {
    fontSize: 12,
    lineHeight: 18,
    color: colors.muted,
    flexShrink: 1,
    textAlign: "center",
  },
  inspectorTabs: {
    marginHorizontal: 16,
    padding: 3,
    borderRadius: 24,
    flexDirection: "row",
    backgroundColor: "#F0F0F1",
  },
  inspectorTab: {
    flex: 1,
    height: 29,
    borderRadius: 17,
    alignItems: "center",
    justifyContent: "center",
  },
  inspectorTabActive: { backgroundColor: "#DFDFE1" },
  inspectorSection: {
    fontSize: 13,
    fontWeight: "500",
    color: colors.text,
    paddingHorizontal: 5,
    marginBottom: 10,
  },
  inspectorEmpty: { fontSize: 12, lineHeight: 19, color: colors.muted, paddingHorizontal: 6 },
  activityRow: {
    flexDirection: "row",
    gap: 10,
    alignItems: "flex-start",
    paddingHorizontal: 5,
    paddingVertical: 12,
    borderRadius: 12,
  },
  activityIcon: {
    width: 31,
    height: 33,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#F0F0F1",
  },
  activityTitle: { color: colors.text, fontSize: 12, lineHeight: 17, fontWeight: "500" },
  activityDetail: { color: colors.muted, fontSize: 11, lineHeight: 16 },
  activityTime: { color: "#929296", fontSize: 10, lineHeight: 15 },
  page: { width: "100%", maxWidth: 1000, alignSelf: "center", padding: 32, paddingBottom: 44 },
  pageTitle: { color: colors.text, fontSize: 26, fontWeight: "600", letterSpacing: -0.8 },
  pageSubtitle: {
    color: colors.muted,
    fontSize: 14,
    lineHeight: 22,
    marginTop: 8,
    marginBottom: 26,
  },
  settings: { gap: 24, alignItems: "flex-start" },
  settingsProfile: { flex: 1, minWidth: 0, gap: 22 },
  settingsAside: { width: 292, gap: 22 },
  appearance: { borderWidth: 1, borderColor: colors.line, gap: 16 },
  avatarOptions: { flexDirection: "row", gap: 10, justifyContent: "center" },
  avatarOption: { padding: 6, borderWidth: 2, borderRadius: 18 },
});
