import { StyleSheet } from "react-native";
import type { ThemeColors } from "./theme-palette";

export const desktopStyles = (colors: ThemeColors) =>
  StyleSheet.create({
    shell: { flex: 1, flexDirection: "row", minHeight: 0, backgroundColor: colors.canvas },
    rail: {
      width: 68,
      borderRightWidth: 1,
      borderRightColor: colors.line,
      paddingVertical: 18,
      alignItems: "center",
      justifyContent: "space-between",
    },
    railPrimary: {
      flex: 1,
      width: "100%",
      alignItems: "center",
      justifyContent: "center",
      paddingBottom: 48,
    },
    railNavigation: { gap: 11 },
    railUtilities: { gap: 12 },
    railItem: {
      width: 42,
      height: 42,
      borderRadius: 22,
      alignItems: "center",
      justifyContent: "center",
    },
    sidebar: {
      width: 284,
      flexShrink: 0,
      borderRightWidth: 1,
      borderRightColor: colors.line,
      paddingTop: 22,
      backgroundColor: colors.raised,
    },
    sideChatToolbar: { flexDirection: "row", alignItems: "center", paddingHorizontal: 12, gap: 5 },
    search: {
      flex: 1,
      flexDirection: "row",
      alignItems: "center",
      backgroundColor: colors.subtle,
      borderRadius: 22,
      gap: 7,
      paddingHorizontal: 11,
      height: 40,
    },
    searchInput: { flex: 1, minWidth: 0, color: colors.text, fontSize: 14, paddingVertical: 4 },
    menuButton: {
      width: 30,
      height: 30,
      borderRadius: 15,
      alignItems: "center",
      justifyContent: "center",
    },
    conversations: { flex: 1, minHeight: 0 },
    sectionLabel: { color: colors.muted, fontSize: 12, fontWeight: "600" },
    conversationItem: {
      minHeight: 54,
      borderRadius: 14,
      paddingHorizontal: 12,
      paddingVertical: 13,
      borderWidth: 1,
      borderColor: "transparent",
      gap: 10,
      flexDirection: "row",
      alignItems: "center",
    },
    conversationLabel: { fontSize: 14, color: colors.text, lineHeight: 20 },
    conversationDate: { color: colors.muted, fontSize: 11 },
    selectedConversation: { backgroundColor: colors.selected, borderColor: colors.selectedBorder },
    sideChatEmpty: {
      flex: 1,
      justifyContent: "center",
      alignItems: "center",
      paddingHorizontal: 22,
      gap: 11,
      paddingBottom: 38,
    },
    sideChatEmptyTitle: {
      fontSize: 13,
      color: colors.text,
      fontWeight: "500",
      textAlign: "center",
    },
    sideChatEmptyCopy: {
      fontSize: 12,
      color: colors.muted,
      textAlign: "center",
      lineHeight: 18,
      marginBottom: 5,
    },
    activeItem: { backgroundColor: colors.selected },
    main: { flex: 1, minWidth: 0, minHeight: 0, backgroundColor: colors.canvas },
    floatingHeader: { position: "absolute", top: 0, left: 0, right: 0, height: 118, zIndex: 3 },
    chatControls: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      paddingHorizontal: 16,
      paddingTop: 16,
    },
    conversationPill: {
      maxWidth: "100%",
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
      minHeight: 36,
      paddingHorizontal: 11,
      borderRadius: 22,
      backgroundColor: colors.card,
      shadowColor: colors.shadow,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.06,
      shadowRadius: 10,
    },
    conversationPillText: { flexShrink: 1, fontSize: 13, color: colors.text, fontWeight: "500" },
    titleBack: {
      width: 34,
      height: 34,
      borderRadius: 17,
      backgroundColor: colors.card,
      alignItems: "center",
      justifyContent: "center",
    },
    header: {
      minHeight: 66,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      gap: 20,
      paddingHorizontal: 28,
      paddingVertical: 14,
    },
    headerTitle: { color: colors.text, fontSize: 16, fontWeight: "500", letterSpacing: -0.3 },
    headerActions: { flexDirection: "row", alignItems: "center", gap: 12 },
    chatHeader: { minHeight: 58, height: 58, paddingHorizontal: 20, paddingVertical: 10 },
    notification: { position: "relative" },
    badge: {
      width: 6,
      height: 6,
      borderRadius: 3,
      position: "absolute",
      right: 9,
      top: 9,
      backgroundColor: colors.blueDark,
      borderColor: colors.canvas,
      borderWidth: 1,
    },
    content: { flex: 1, minHeight: 0 },
    chat: {
      flex: 1,
      width: "100%",
      maxWidth: 896,
      alignSelf: "center",
      minHeight: 0,
      paddingHorizontal: 28,
      paddingBottom: 20,
    },
    inspector: {
      width: 330,
      flexShrink: 0,
      borderLeftWidth: 1,
      borderLeftColor: colors.line,
      backgroundColor: colors.canvas,
    },
    inspectorToolbar: {
      flexDirection: "row",
      justifyContent: "flex-end",
      alignItems: "center",
      paddingHorizontal: 14,
      paddingTop: 12,
      height: 42,
    },
    inspectorProfile: {
      alignItems: "center",
      paddingHorizontal: 24,
      paddingTop: 12,
      paddingBottom: 38,
      gap: 7,
    },
    inspectorPortrait: {
      width: 98,
      height: 98,
      borderRadius: 49,
      backgroundColor: colors.subtle,
      marginBottom: 3,
    },
    portraitEdit: {
      position: "absolute",
      right: -1,
      bottom: 0,
      width: 30,
      height: 30,
      borderRadius: 16,
      backgroundColor: colors.canvas,
      borderWidth: 3,
      borderColor: colors.canvas,
      justifyContent: "center",
      alignItems: "center",
    },
    inspectorName: { color: colors.text, fontSize: 21, fontWeight: "500", letterSpacing: -0.6 },
    inspectorStatus: {
      fontSize: 12,
      lineHeight: 18,
      color: colors.muted,
      flexShrink: 1,
      textAlign: "center",
    },
    inspectorTabs: {
      marginHorizontal: 16,
      padding: 3,
      borderRadius: 24,
      flexDirection: "row",
      backgroundColor: colors.subtle,
    },
    inspectorTab: {
      flex: 1,
      height: 29,
      borderRadius: 17,
      alignItems: "center",
      justifyContent: "center",
    },
    inspectorTabActive: {
      backgroundColor: colors.card,
      shadowColor: colors.shadow,
      shadowOpacity: 0.06,
      shadowRadius: 6,
      shadowOffset: { width: 0, height: 2 },
    },
    inspectorSection: {
      fontSize: 13,
      fontWeight: "500",
      color: colors.text,
      paddingHorizontal: 5,
      marginBottom: 10,
    },
    inspectorEmpty: { fontSize: 12, lineHeight: 19, color: colors.muted, paddingHorizontal: 6 },
    activityRow: {
      flexDirection: "row",
      gap: 10,
      alignItems: "flex-start",
      paddingHorizontal: 5,
      paddingVertical: 13,
      borderRadius: 14,
    },
    activityIcon: {
      width: 31,
      height: 33,
      borderRadius: 10,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: colors.subtle,
    },
    activityTitle: { color: colors.text, fontSize: 14, lineHeight: 19, fontWeight: "500" },
    activityDetail: { color: colors.muted, fontSize: 12, lineHeight: 18 },
    activityTime: { color: colors.muted, fontSize: 10, lineHeight: 15 },
    page: {
      width: "100%",
      maxWidth: 900,
      alignSelf: "center",
      paddingHorizontal: 36,
      paddingTop: 56,
      paddingBottom: 44,
    },
    pageTitle: { color: colors.text, fontSize: 26, fontWeight: "600", letterSpacing: -0.8 },
    pageSubtitle: {
      color: colors.muted,
      fontSize: 14,
      lineHeight: 22,
      marginTop: 8,
      marginBottom: 26,
    },
    settings: { gap: 24, alignItems: "flex-start" },
    settingsProfile: { flex: 1, minWidth: 0, gap: 22 },
    settingsAside: { width: 292, gap: 22 },
    appearance: { borderWidth: 1, borderColor: colors.line, gap: 16 },
    avatarOptions: { flexDirection: "row", gap: 10, justifyContent: "center" },
    avatarOption: { padding: 6, borderWidth: 2, borderRadius: 18 },
  });
