export const learningPtBR: Record<string, string> = {
  "Review every hour": "Revisar a cada hora",
  "1 hour": "1 hora",
  "Retry learning review": "Tentar revisar o aprendizado novamente",
  Proactivity: "Proatividade",
  "Automatic learning": "Aprendizado automático",
  "Useful facts and preferences are reviewed after conversations. Corrections update existing memories; verified methods become reusable procedures.":
    "Fatos úteis e preferências são revisados após as conversas. Correções atualizam as memórias existentes; métodos verificados viram procedimentos reutilizáveis.",
  "Learning enabled": "Aprendizado ativado",
  "Learning disabled": "Aprendizado desativado",
  "Paused with the assistant": "Pausado junto com o assistente",
  "Review in progress": "Revisão em andamento",
  "Last review: {date}": "Última revisão: {date}",
  "Next review: {date}": "Próxima revisão: {date}",
  "Not yet reviewed": "Ainda não revisado",
  "Revisit unfinished plans and work, and flag important emails before their deadlines. Suggestions appear in your main conversation.":
    "Retoma planos e trabalhos pendentes e destaca e-mails importantes antes dos prazos. As sugestões aparecem na conversa principal.",
  "Proactive reviews": "Revisões proativas",
  "Review every {hours} hours": "Revisar a cada {hours} horas",
  "15 minutes": "15 minutos",
  "{hours} hours": "{hours} horas",
  "Proactive reviews disabled": "Revisões proativas desativadas",
  "Sources checked": "Fontes verificadas",
  "Review now": "Revisar agora",
  "Review source: mail": "E-mail",
  "Review source: calendar": "Calendário",
  "Review source: goals": "Planos",
  "Review source: tasks": "Tarefas",
  "Review source: memories": "Memórias",
  "Review source: reasoning": "Avaliação das pendências",
  "Up to date": "Atualizado",
  "Partially reviewed": "Revisado parcialmente",
  Unavailable: "Indisponível",
  "Mail source is disconnected": "E-mail desconectado",
  "Calendar source is disconnected": "Calendário desconectado",
  "Conversation learning is pending; plan reminders wait for current corrections":
    "A conversa ainda está sendo consolidada; os lembretes de planos aguardam as correções mais recentes.",
  "Learned from your conversation": "Aprendido na sua conversa",
  learning: "aprendizado automático",
  fact: "fato",
  preference: "preferência",
  habit: "hábito",
  plan: "plano",
  "Follow-up: open": "Plano em aberto",
  "Follow-up: resolved": "Plano concluído",
  "Follow-up: cancelled": "Plano cancelado",
  "Source quote": "Trecho de origem",
};
