export const museInterfacePTBR: Record<string, string> = {
  "Expand workspace": "Expandir espaço de trabalho",
  "Show conversation": "Mostrar conversa",
  "Loading preview…": "Carregando prévia…",
  "Could not load this preview.": "Não foi possível carregar esta prévia.",
  "Preview unavailable": "Prévia indisponível",
  "Open task": "Abrir tarefa",
  "For you": "Para você",
  "Feed activity and settings": "Atividade e ajustes do feed",
  "Let's discuss: {title}\n\n{body}": "Vamos conversar sobre: {title}\n\n{body}",
  Discuss: "Conversar",
  "View details": "Ver detalhes",
  "Your day, coming together": "Seu dia tomando forma",
  "Updates from your tasks and the things you follow will appear here.":
    "As novidades das suas tarefas e do que você acompanha aparecem aqui.",
  "No tasks here yet.": "Nenhuma tarefa por aqui ainda.",
  Automations: "Automações",
  Tasks: "Tarefas",
  "Reviews & receipts": "Revisões e comprovantes",
  "In progress": "Em andamento",
  Finished: "Concluídas",
  "Resume automations": "Retomar automações",
  "Pause automations": "Pausar automações",
  "Global pause saved": "Pausa geral salva",
  "New automation is paused. Operations already in progress may still finish.":
    "Novas automações estão pausadas. Operações já em andamento ainda podem terminar.",
  tasks: "tarefas",
  "operations active": "operações ativas",
  uncertain: "incertas",
  "Loading saved progress…": "Carregando o progresso salvo…",
  Started: "Iniciadas",
  "Your request": "Seu pedido",
  "This step has no additional details.": "Esta etapa não tem detalhes adicionais.",
  "Back to summary": "Voltar ao resumo",
  Summary: "Resumo",
  "Task settings": "Ajustes da tarefa",
  Completed: "Concluído",
  "Find ideas": "Buscar ideias",
  "Room for a good idea": "Espaço para uma boa ideia",
  "Find ideas from the sources you have granted access to. Each suggestion includes its evidence.":
    "Encontre ideias nas fontes que você autorizou. Cada sugestão inclui suas referências.",
  "What should your agent do?": "O que seu agente deve fazer?",
  "Start this": "Começar",
  "Keep edits": "Manter alterações",
  Dismiss: "Dispensar",
  Family: "Família",
  Travel: "Viagens",
  Health: "Saúde",
  Finances: "Finanças",
  "Checking every {minutes} minutes": "Verificando a cada {minutes} minutos",
  "Create a goal": "Criar uma meta",
  "Expand goal": "Expandir meta",
  "Goal details": "Detalhes da meta",
  Artifacts: "Criações",
  "Your goal's results will appear here.": "Os resultados da sua meta aparecem aqui.",
  milestones: "etapas",
  "Goal created": "Meta criada",
  "Notification details": "Detalhes da notificação",
  Read: "Lida",
  "Mark read": "Marcar como lida",
  "Search apps": "Buscar aplicativos",
  "Search connectors": "Buscar conexões",
  "On your computer": "No seu computador",
  Manage: "Gerenciar",
  Routines: "Rotinas",
  "Things your agent does regularly": "O que seu agente faz regularmente",
  Playbooks: "Guias de trabalho",
  "Your saved ways of doing things": "Suas formas de fazer as coisas",
  "Choose how updates reach you": "Escolha como receber novidades",
  "File history": "Histórico de arquivos",
  "Review and restore saved versions": "Revise e restaure versões salvas",
  "Personality & memory": "Personalidade e memória",
  "Make your agent feel like yours": "Deixe seu agente com a sua cara",
  "Read messages and prepare replies": "Leia mensagens e prepare respostas",
  "Events and reviewed invitations": "Eventos e convites revisados",
  "Persistent browser sessions": "Sessões salvas do navegador",
  "PDFs, forms and filled copies": "PDFs, formulários e cópias preenchidas",
  Feed: "Feed",
  General: "Geral",
  Connectors: "Conexões",
  Personalization: "Personalização",
  Permissions: "Permissões",
  Language: "Idioma",
  "Close settings": "Fechar configurações",
  "Back to settings": "Voltar às configurações",
  "Customize your companion": "Personalizar seu companheiro",
  "Open notifications": "Abrir notificações",
  "Review requests before your assistant takes an action on your behalf.":
    "Revise os pedidos antes de seu assistente realizar uma ação em seu nome.",
  "Needs review": "Precisa de revisão",
  "Nothing needs your approval right now.": "Nada precisa da sua aprovação agora.",
  "Approvals history": "Histórico de aprovações",
  "Close details": "Fechar detalhes",
  Search: "Buscar",
  "Search your workspace": "Buscar no seu espaço",
  "Close search": "Fechar busca",
  "Search results": "Resultados da busca",
  Recent: "Recentes",
  "No results found.": "Nenhum resultado encontrado.",
  Appearance: "Aparência",
  Upcoming: "Próximas atividades",
  "App menu": "Menu do aplicativo",
  "Download Android app": "Baixar aplicativo Android",
  Reply: "Responder",
  Copy: "Copiar",
  Copied: "Copiado",
  Share: "Compartilhar",
  "Message actions": "Ações da mensagem",
  "Could not copy this message.": "Não foi possível copiar esta mensagem.",
  "Could not share this message.": "Não foi possível compartilhar esta mensagem.",
  "Search conversations": "Buscar conversas",
  "Conversation actions": "Ações da conversa",
  "More options": "Mais opções",
  "No conversations found.": "Nenhuma conversa encontrada.",
  "Workspace tools": "Ferramentas do espaço",
  Chats: "Conversas",
  "Upload file": "Enviar arquivo",
  Camera: "Câmera",
  "Saved files": "Arquivos salvos",
  "All artifacts": "Todas as criações",
  Documents: "Documentos",
  "Web artifacts": "Criações web",
  Images: "Imagens",
  Videos: "Vídeos",
  Audio: "Áudio",
  Media: "Mídia",
  "Search library": "Buscar na biblioteca",
  "List view": "Visualização em lista",
  "Grid view": "Visualização em grade",
  "Document preview": "Prévia do documento",
  "More options for {name}": "Mais opções para {name}",
  "No matching files": "Nenhum arquivo encontrado",
  "Your library starts here": "Sua biblioteca começa aqui",
  "Try another name or file type.": "Tente outro nome ou tipo de arquivo.",
  "Documents, images and things you create will be kept here.":
    "Documentos, imagens e suas criações ficam aqui.",
  "Fit width": "Ajustar à largura",
  "Edit event": "Editar evento",
  "Create event": "Criar evento",
  Available: "Disponíveis",
  "Directing this message to {name}": "Direcionando esta mensagem para {name}",
  "Send to chat": "Enviar para a conversa",
};
