export const museInterfacePTBR: Record<string, string> = {
  Saved: "Salvas",
  Forgotten: "Esquecidas",
  Expired: "Expiradas",
  All: "Todas",
  "Choose an app and sign in with your account. You can disconnect it whenever you want.":
    "Escolha um aplicativo e entre com a sua conta. Você pode desconectar quando quiser.",
  "Search connections": "Buscar conexões",
  "Google, Gmail, calendar…": "Google, Gmail, agenda…",
  "Hide advanced connections": "Ocultar conexões avançadas",
  "Advanced connections": "Conexões avançadas",
  "Google sign-in is not enabled on this server yet. The administrator needs to finish the app setup.":
    "A conexão com o Google ainda não está disponível. O responsável pelo aplicativo precisa concluir a configuração.",
  "Choose your Google account. This screen updates when you return.":
    "Escolha sua conta Google. Esta tela será atualizada quando você voltar.",
  "Switch Google account": "Trocar conta Google",
  "Could not open Google sign-in. Try again.":
    "Não foi possível abrir o login do Google. Tente novamente.",
  "Install app": "Instalar aplicativo",
  "Okami on your phone": "Okami no seu celular",
  "Download the Android app and open the file to install it. Your conversations stay in the same workspace.":
    "Baixe o aplicativo Android e abra o arquivo para instalar. Suas conversas continuam no mesmo espaço.",
  "Android may ask you to allow installation from your browser.":
    "O Android pode pedir permissão para instalar pelo navegador.",
  "Open this site in Safari, tap Share, then Add to Home Screen. There is no iOS store download yet.":
    "Abra este site no Safari, toque em Compartilhar e em Adicionar à Tela de Início. Ainda não há aplicativo na loja do iOS.",
  "Could not open the download. Try again.": "Não foi possível abrir o download. Tente novamente.",
  "Review what your assistant remembers. You decide what stays.":
    "Veja o que seu assistente lembra. Você decide o que fica.",
  "Add memory": "Adicionar memória",
  "What should I remember?": "O que devo lembrar?",
  "Expiration date (optional)": "Data de validade (opcional)",
  "YYYY-MM-DD · leave empty to keep it": "AAAA-MM-DD · deixe vazio para manter",
  "Choose a future date in YYYY-MM-DD format.": "Escolha uma data futura no formato AAAA-MM-DD.",
  "Save memory": "Salvar memória",
  "Search memories": "Buscar memórias",
  "Search facts, preferences or plans": "Busque fatos, preferências ou planos",
  "Loading memories": "Carregando memórias",
  "No matching memories": "Nenhuma memória encontrada",
  "No saved memories yet": "Nenhuma memória salva ainda",
  "No memories here": "Nenhuma memória nesta categoria",
  "Try a different search or another filter.": "Tente outra busca ou outro filtro.",
  "Add a memory, or open Forgotten to restore something you removed.":
    "Adicione uma memória ou abra Esquecidas para restaurar algo que você removeu.",
  "Memories in this category will appear here.": "As memórias desta categoria aparecerão aqui.",
  "Load more memories": "Carregar mais memórias",
  "No saved version is available to restore.": "Não há versão salva disponível para restaurar.",
  "Your assistant no longer uses this memory. Restore it to remember it again.":
    "Seu assistente não usa mais esta memória. Restaure para que ele volte a lembrá-la.",
  "Restore memory": "Restaurar memória",
  "Hide details": "Ocultar detalhes",
  "Details and history": "Detalhes e histórico",
  "Forget this memory? You can restore it later.":
    "Esquecer esta memória? Você pode restaurá-la depois.",
  "Confirm forget": "Confirmar esquecimento",
  "local time": "horário local",
  Remove: "Remover",
  "Clear finished": "Limpar encerradas",
  "Clear finished tasks?": "Limpar tarefas encerradas?",
  "Remove task?": "Remover tarefa?",
  "Remove task: {title}": "Remover tarefa: {title}",
  "Stop and remove task?": "Interromper e remover tarefa?",
  "Stop and remove": "Interromper e remover",
  "This task will stop and leave your activity list. Saved files remain available.":
    "A tarefa será interrompida e removida da atividade. Os arquivos salvos continuam disponíveis.",
  "This task will leave your activity list. Saved files remain available.":
    "A tarefa será removida da atividade. Os arquivos salvos continuam disponíveis.",
  "Completed, failed and cancelled tasks will leave your activity list. Active tasks and saved files remain available.":
    "Tarefas concluídas, com falha e canceladas serão removidas da atividade. As tarefas ativas e os arquivos salvos continuam disponíveis.",
  "The conversation and draft will be deleted. Any reply and unfinished tasks in this conversation will stop. Saved files and memories remain available. This cannot be undone.":
    "A conversa e o rascunho serão excluídos. Respostas e tarefas em andamento nesta conversa serão interrompidas. Os arquivos e as memórias salvos continuam disponíveis. Esta ação não pode ser desfeita.",
  "The conversation is still stopping. Try deleting it again in a moment.":
    "A conversa ainda está sendo interrompida. Tente excluir novamente em instantes.",
  "Stop the reply and finish or cancel this conversation's active tasks before deleting it.":
    "Interrompa a resposta e as tarefas desta conversa antes de excluí-la.",
  "Confirm stopping this task before removing it.":
    "Confirme a interrupção da tarefa antes de removê-la.",
  "Not completed": "Não concluída",
  "Execution progress": "Progresso da execução",
  "Preparing the requested work": "Preparando a execução",
  "Deliver the result": "Entregar o resultado",
  "Result not verified": "Resultado não verificado",
  "Delivery verified": "Entrega verificada",
  "Partial delivery": "Entrega parcial",
  "Retry task": "Tentar novamente",
  Sources: "Fontes",
  "The available result is partial; some requested facts or actions could not be verified.":
    "A entrega ficou incompleta. Alguns dados ou ações pedidos não puderam ser verificados.",
  "Image requests can use this connected ChatGPT account.":
    "Os pedidos de imagem podem usar esta conta conectada do ChatGPT.",
  "Sign in on OpenAI’s page using the code below.":
    "Entre na página da OpenAI usando o código abaixo.",
  "Connect your ChatGPT account through Codex to generate images.":
    "Conecte sua conta do ChatGPT pelo Codex para gerar imagens.",
  Failed: "Não concluída",
  Cancelled: "Cancelada",
  Scheduled: "Agendada",
  Queued: "Na fila",
  Running: "Em andamento",
  Succeeded: "Concluída",
  "Waiting input": "Aguardando resposta",
  "Waiting approval": "Aguardando aprovação",
  "Waiting resource": "Aguardando recurso",
  "Waiting job": "Em andamento",
  "Waiting provider": "Aguardando provedor",
  "Waiting children": "Aguardando subtarefas",
  "Waiting global pause": "Pausa geral",
  "Agent updates unavailable.": "Atualizações do assistente indisponíveis.",
  "Reconnect agent": "Reconectar assistente",
  "Your assistant is reconnecting. Saved work will continue when it is available.":
    "Seu assistente está reconectando. As tarefas salvas continuam quando ele estiver disponível.",
  "Not checked yet": "Ainda não verificado",
  "ChatGPT images": "Imagens com ChatGPT",
  "Connected with Codex": "Conectado pelo Codex",
  "Your ChatGPT subscription": "Sua assinatura do ChatGPT",
  "Connect your ChatGPT account through Codex to generate images. Sign in on OpenAI’s page using the code below.":
    "Conecte sua conta do ChatGPT pelo Codex para gerar imagens. Entre na página da OpenAI usando o código abaixo.",
  "Disconnect image generation? Your conversation model connection stays available.":
    "Desconectar a geração de imagens? A conexão do modelo de conversa continua disponível.",
  "Your connection code": "Seu código de conexão",
  "Open OpenAI sign-in": "Abrir login da OpenAI",
  "Waiting for you to finish connecting. This screen updates automatically.":
    "Aguardando você concluir a conexão. Esta tela atualiza automaticamente.",
  "Cancel connection": "Cancelar conexão",
  "Connect ChatGPT for images": "Conectar ChatGPT para imagens",
  "This code expired. Start a new connection.": "Este código expirou. Inicie uma nova conexão.",
  "Could not connect this account. Try again.":
    "Não foi possível conectar esta conta. Tente novamente.",

  Models: "Modelos",
  "Conversation model": "Modelo de conversa",
  "Choose the model for new replies and tasks. Your connected accounts determine what is available.":
    "Escolha o modelo para novas respostas e tarefas. As contas conectadas determinam o que está disponível.",
  Automatic: "Automático",
  "Use the default model and available fallbacks":
    "Usar o modelo padrão e as alternativas disponíveis",
  "Account not connected": "Conta não conectada",
  "Currently using: {model}": "Em uso: {model}",
  "Save model": "Salvar modelo",
  "Model saved. Your next reply will use this preference.":
    "Modelo salvo. A próxima resposta seguirá esta preferência.",
  "Connected services": "Serviços conectados",
  "Not available": "Indisponível",
  "Update your API key": "Atualize sua chave de API",
  "Not connected": "Não conectado",
  "Search the web with Tavily using your own API key.":
    "Pesquise na web com o Tavily usando sua chave de API.",
  "Update key": "Atualizar chave",
  Disconnect: "Desconectar",
  "Remove the saved Tavily key? Web search will use the other available sources.":
    "Remover a chave salva do Tavily? A pesquisa usará as outras fontes disponíveis.",
  "Disconnect Tavily": "Desconectar Tavily",
  "Connect Tavily": "Conectar Tavily",
  "API key": "Chave de API",
  "Save your API key in the private vault to enable Tavily web search. Your key is never sent to the conversation or model.":
    "Salve sua chave de API no cofre privado para ativar a pesquisa com o Tavily. A chave não é enviada à conversa nem ao modelo.",
  "Chat and other tasks remain available.": "A conversa e as outras tarefas continuam disponíveis.",
  "Conversation actions: {name}": "Ações da conversa: {name}",
  "Delete conversation?": "Excluir conversa?",
  "Delete conversation": "Excluir conversa",
  "Rename conversation": "Renomear conversa",
  "The conversation and its draft will be deleted. Saved files, tasks and memories stay available. This cannot be undone.":
    "A conversa e seu rascunho serão excluídos. Os arquivos, as tarefas e as memórias salvos continuam disponíveis. Esta ação não pode ser desfeita.",
  "Start a side chat": "Comece uma conversa separada",
  "Archived conversations stay saved and can be restored here.":
    "As conversas arquivadas ficam salvas e podem ser restauradas aqui.",
  "Side chats are an optional way to organize your conversations by topic.":
    "Use conversas separadas para organizar seus assuntos.",
  "Recent work": "Trabalhos recentes",
  "Could not finish this task. Open it to review or try again.":
    "Não foi possível concluir esta tarefa. Abra para revisar ou tentar novamente.",
  "Your input is needed": "Precisa da sua resposta",
  "Show more updates": "Ver mais novidades",
  Tracking: "Acompanhamentos",
  Track: "Acompanhar",
  "Open tracking: {title}": "Abrir acompanhamento: {title}",
  "Follow a price or a page. Your assistant will let you know when something changes.":
    "Acompanhe um preço ou uma página. Seu assistente avisa quando houver mudanças.",
  "What would you like to work toward? Add a goal and take it one step at a time.":
    "O que você quer conquistar? Crie uma meta e avance um passo de cada vez.",
  "Show less": "Mostrar menos",
  "Show {count} more": "Mostrar mais {count}",
  "Create a goal: {category}": "Criar meta: {category}",
  Relationships: "Relacionamentos",
  "Something else": "Outra meta",
  "Track something": "Novo acompanhamento",
  "Your goal": "Sua meta",
  "What does success look like?": "Qual resultado você quer alcançar?",
  "Milestones (one per line)": "Etapas (uma por linha)",
  "Build a three-month emergency fund": "Criar uma reserva para três meses de despesas",
  "Create goal": "Criar meta",
  "Complete goal": "Concluir meta",
  "Plan next steps": "Planejar próximos passos",
  "What are you watching?": "O que você quer acompanhar?",
  "Try the built-in availability page": "Testar com a página de demonstração",
  "Public page URL": "Endereço da página pública",
  "Check every (minutes)": "Verificar a cada (minutos)",
  "Exact product name": "Nome exato do produto",
  "Currency (EUR, USD, BRL...)": "Moeda (EUR, USD, BRL...)",
  "A table at my favorite restaurant": "Uma mesa no meu restaurante favorito",
  "Notify me when": "Avise quando",
  "Page changes": "A página mudar",
  "Text appears": "Um texto aparecer",
  "Price drops below": "O preço cair abaixo de",
  "Text to look for": "Texto para procurar",
  "Target price": "Preço desejado",
  "Changes to this built-in page stay in your workspace.":
    "As alterações desta página de demonstração ficam no seu espaço.",
  "OkamiBot checks this public page on the server and saves meaningful changes in Notifications.":
    "O OkamiBot acompanha a página e avisa nas notificações quando houver mudanças relevantes.",
  "Use a check interval from 1 to 10080 minutes.": "Use um intervalo de 1 a 10080 minutos.",
  "Enter an http or https address for a public page.":
    "Informe um endereço http ou https de uma página pública.",
  "Start tracking": "Começar acompanhamento",
  "Built-in availability page": "Página de disponibilidade de demonstração",
  "Watch for a page change": "Avisar quando a página mudar",
  "Watch for “{value}”": "Avisar quando aparecer “{value}”",
  "Price below {value}": "Preço abaixo de {value}",
  "Every {minutes} min · {count} checks": "A cada {minutes} min · {count} verificações",
  "Last check: {date}": "Última verificação: {date}",
  "Next check: {date}": "Próxima verificação: {date}",
  "Partial comparison. Open the source for the full content.":
    "Comparação parcial. Abra a fonte para ver o conteúdo completo.",
  "Check now": "Verificar agora",
  "Stop tracking": "Encerrar acompanhamento",
  "Change availability": "Alterar disponibilidade",
  Today: "Hoje",

  "Expand workspace": "Expandir espaço de trabalho",
  "Show conversation": "Mostrar conversa",
  "Loading preview…": "Carregando prévia…",
  "Could not load this preview.": "Não foi possível carregar esta prévia.",
  "Preview unavailable": "Prévia indisponível",
  "Open task": "Abrir tarefa",
  "For you": "Para você",
  "Feed activity and settings": "Atividade e ajustes do feed",
  "Let's discuss: {title}\n\n{body}": "Vamos conversar sobre: {title}\n\n{body}",
  Discuss: "Conversar",
  "View details": "Ver detalhes",
  "Your day, coming together": "Seu dia tomando forma",
  "Updates from your tasks and the things you follow will appear here.":
    "As novidades das suas tarefas e do que você acompanha aparecem aqui.",
  "No tasks here yet.": "Nenhuma tarefa por aqui ainda.",
  Automations: "Automações",
  Tasks: "Tarefas",
  "Reviews & receipts": "Revisões e comprovantes",
  "In progress": "Em andamento",
  Finished: "Concluídas",
  "Resume automations": "Retomar automações",
  "Pause automations": "Pausar automações",
  "Global pause saved": "Pausa geral salva",
  "New automation is paused. Operations already in progress may still finish.":
    "Novas automações estão pausadas. Operações já em andamento ainda podem terminar.",
  tasks: "tarefas",
  "operations active": "operações ativas",
  uncertain: "incertas",
  "Loading saved progress…": "Carregando o progresso salvo…",
  Started: "Iniciadas",
  "Your request": "Seu pedido",
  "This step has no additional details.": "Esta etapa não tem detalhes adicionais.",
  "Back to summary": "Voltar ao resumo",
  Summary: "Resumo",
  "Task settings": "Ajustes da tarefa",
  Completed: "Concluído",
  "Find ideas": "Buscar ideias",
  "Room for a good idea": "Espaço para uma boa ideia",
  "Find ideas from the sources you have granted access to. Each suggestion includes its evidence.":
    "Encontre ideias nas fontes que você autorizou. Cada sugestão inclui suas referências.",
  "What should your agent do?": "O que seu agente deve fazer?",
  "Start this": "Começar",
  "Keep edits": "Manter alterações",
  Dismiss: "Dispensar",
  Family: "Família",
  Travel: "Viagens",
  Health: "Saúde",
  Finances: "Finanças",
  "Checking every {minutes} minutes": "Verificando a cada {minutes} minutos",
  "Create a goal": "Criar uma meta",
  "Expand goal": "Expandir meta",
  "Goal details": "Detalhes da meta",
  Artifacts: "Criações",
  "Your goal's results will appear here.": "Os resultados da sua meta aparecem aqui.",
  milestones: "etapas",
  "Goal created": "Meta criada",
  "Notification details": "Detalhes da notificação",
  Read: "Lida",
  "Mark read": "Marcar como lida",
  "Search apps": "Buscar aplicativos",
  "Search connectors": "Buscar conexões",
  "On your computer": "No seu computador",
  Manage: "Gerenciar",
  Routines: "Rotinas",
  "Things your agent does regularly": "O que seu agente faz regularmente",
  Playbooks: "Guias de trabalho",
  "Your saved ways of doing things": "Suas formas de fazer as coisas",
  "Choose how updates reach you": "Escolha como receber novidades",
  "File history": "Histórico de arquivos",
  "Review and restore saved versions": "Revise e restaure versões salvas",
  "Personality & memory": "Personalidade e memória",
  "Make your agent feel like yours": "Deixe seu agente com a sua cara",
  "Read messages and prepare replies": "Leia mensagens e prepare respostas",
  "Events and reviewed invitations": "Eventos e convites revisados",
  "Persistent browser sessions": "Sessões salvas do navegador",
  "PDFs, forms and filled copies": "PDFs, formulários e cópias preenchidas",
  Feed: "Feed",
  General: "Geral",
  Connectors: "Conexões",
  Personalization: "Personalização",
  Permissions: "Permissões",
  Language: "Idioma",
  "Close settings": "Fechar configurações",
  "Back to settings": "Voltar às configurações",
  "Customize your companion": "Personalizar seu companheiro",
  "Open notifications": "Abrir notificações",
  "Review requests before your assistant takes an action on your behalf.":
    "Revise os pedidos antes de seu assistente realizar uma ação em seu nome.",
  "Needs review": "Precisa de revisão",
  "Nothing needs your approval right now.": "Nada precisa da sua aprovação agora.",
  "Approvals history": "Histórico de aprovações",
  "Close details": "Fechar detalhes",
  Search: "Buscar",
  "Search your workspace": "Buscar no seu espaço",
  "Close search": "Fechar busca",
  "Search results": "Resultados da busca",
  Recent: "Recentes",
  "No results found.": "Nenhum resultado encontrado.",
  Appearance: "Aparência",
  Upcoming: "Próximas atividades",
  "App menu": "Menu do aplicativo",
  "Download Android app": "Baixar aplicativo Android",
  Reply: "Responder",
  Copy: "Copiar",
  Copied: "Copiado",
  Share: "Compartilhar",
  "Message actions": "Ações da mensagem",
  "Could not copy this message.": "Não foi possível copiar esta mensagem.",
  "Could not share this message.": "Não foi possível compartilhar esta mensagem.",
  "Search conversations": "Buscar conversas",
  "Conversation actions": "Ações da conversa",
  "More options": "Mais opções",
  "No conversations found.": "Nenhuma conversa encontrada.",
  "Workspace tools": "Ferramentas do espaço",
  Chats: "Conversas",
  "Upload file": "Enviar arquivo",
  Camera: "Câmera",
  "Saved files": "Arquivos salvos",
  "All artifacts": "Todas as criações",
  Documents: "Documentos",
  "Web artifacts": "Criações web",
  Images: "Imagens",
  Videos: "Vídeos",
  Audio: "Áudio",
  Media: "Mídia",
  "Search library": "Buscar na biblioteca",
  "List view": "Visualização em lista",
  "Grid view": "Visualização em grade",
  "Document preview": "Prévia do documento",
  "More options for {name}": "Mais opções para {name}",
  "No matching files": "Nenhum arquivo encontrado",
  "Your library starts here": "Sua biblioteca começa aqui",
  "Try another name or file type.": "Tente outro nome ou tipo de arquivo.",
  "Documents, images and things you create will be kept here.":
    "Documentos, imagens e suas criações ficam aqui.",
  "Fit width": "Ajustar à largura",
  "Edit event": "Editar evento",
  "Create event": "Criar evento",
  Available: "Disponíveis",
  "Directing this message to {name}": "Direcionando esta mensagem para {name}",
  "Send to chat": "Enviar para a conversa",
};
